[project]
name = "assistente-python"
version = "0.1.0"
description = "Assistente de programação focado em python."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "groq>=1.0.0",
    "streamlit>=1.53.1",
]
